"""API error code constants."""

from enum import Enum


class ApiErrorCode(str, Enum):
    """Stable API error identifiers."""

    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    FILE_INVALID = "FILE_INVALID"
    AI_PROCESSING_FAILED = "AI_PROCESSING_FAILED"
