import { ClinicalService } from "../services/clinicalService";

export const clinicalApi = {
  upload: ClinicalService.upload,
  uploadCase: ClinicalService.uploadCase,
  uploadSingleLegacy: ClinicalService.uploadSingleLegacy,
  encounters: ClinicalService.listEncounters,
  getEncounter: ClinicalService.getEncounter,
  reanalyzeImaging: ClinicalService.reanalyzeImaging,
  regenerateSynthesis: ClinicalService.regenerateSynthesis,
  getCarePlan: ClinicalService.getCarePlan,
  approveCarePlan: ClinicalService.approveCarePlan,
  requestConsult: ClinicalService.requestConsult,
  getConsultConfig: ClinicalService.getConsultConfig,
  finalizeSummary: ClinicalService.finalizeSummary,
  acknowledgeAlert: ClinicalService.acknowledgeAlert,
  deleteEncounter: ClinicalService.deleteEncounter,
  searchPatients: ClinicalService.searchPatients,
  previewPatientId: ClinicalService.previewPatientId,
  triageConverse: ClinicalService.triageConverse,
  triageRoadmap: ClinicalService.triageRoadmap,
  triageGetSession: ClinicalService.triageGetSession,
  triageAddMessage: ClinicalService.triageAddMessage,
  triageFinalize: ClinicalService.triageFinalize,
};
